### ISSUE TITLE
Crash when reporting any crash

### ISSUE THREAD

**Issue by mcatanzaro** [abrt/libreport#584]
I noticed that libreport-2.11.1-1.fc31 is unable to report crashes. It gets close to the end of the crash report process and then it crashes itself.

The first time I noticed this, I tried to report the crash using ABRT, but of course it just crashed again while trying to do so.

The gdb backtrace I got was not actionable, because it indicated memory corruption, so I got a trace with valgrind instead:

```
==20950== Invalid free() / delete / delete[] / realloc()
==20950==    at 0x4839A0C: free (vg_replace_malloc.c:540)
==20950==    by 0x53AF77F: g_list_foreach (glist.c:1069)
==20950==    by 0x53AF7AE: g_list_free_full (glist.c:223)
==20950==    by 0x116B54: ??? (in /usr/bin/report-gtk)
==20950==    by 0x118BF9: ??? (in /usr/bin/report-gtk)
==20950==    by 0x1190FD: ??? (in /usr/bin/report-gtk)
==20950==    by 0x53B349F: g_main_dispatch (gmain.c:3179)
==20950==    by 0x53B349F: g_main_context_dispatch (gmain.c:3844)
==20950==    by 0x53B382F: g_main_context_iterate.isra.0 (gmain.c:3917)
==20950==    by 0x53B38D2: g_main_context_iteration (gmain.c:3978)
==20950==    by 0x520AC74: g_application_run (gapplication.c:2559)
==20950==    by 0x1130C3: ??? (in /usr/bin/report-gtk)
==20950==    by 0x54ED1A2: (below main) (libc-start.c:308)
==20950==  Address 0x17202a80 is 0 bytes inside a block of size 16 free'd
==20950==    at 0x4839A0C: free (vg_replace_malloc.c:540)
==20950==    by 0x116B41: ??? (in /usr/bin/report-gtk)
==20950==    by 0x118BF9: ??? (in /usr/bin/report-gtk)
==20950==    by 0x1190FD: ??? (in /usr/bin/report-gtk)
==20950==    by 0x53B349F: g_main_dispatch (gmain.c:3179)
==20950==    by 0x53B349F: g_main_context_dispatch (gmain.c:3844)
==20950==    by 0x53B382F: g_main_context_iterate.isra.0 (gmain.c:3917)
==20950==    by 0x53B38D2: g_main_context_iteration (gmain.c:3978)
==20950==    by 0x520AC74: g_application_run (gapplication.c:2559)
==20950==    by 0x1130C3: ??? (in /usr/bin/report-gtk)
==20950==    by 0x54ED1A2: (below main) (libc-start.c:308)
==20950==  Block was alloc'd at
==20950==    at 0x483880B: malloc (vg_replace_malloc.c:309)
==20950==    by 0x5555F2E: strdup (strdup.c:42)
==20950==    by 0x487EDE1: libreport_xstrdup (in /usr/lib64/libreport.so.0.0.1)
==20950==    by 0x4897FFF: wf_get_event_names (in /usr/lib64/libreport.so.0.0.1)
==20950==    by 0x113186: ??? (in /usr/bin/report-gtk)
==20950==    by 0x54ED1A2: (below main) (libc-start.c:308)
```

**Comment by mcatanzaro** [comment]
The missing frames are caused by a weird mismatch between the package versions available in F31. F31 has libreport-gtk-2.11.1-1.fc31 but only libreport-gtk-debuginfo-2.10.1-2.fc31. I don't know how to explain that. Seems like an infrastructure bug.

Here's the gdb version of the backtrace, which fills in a couple of the missing frames for the second free but does nothing to help us figure out where the string was first freed:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f2f874aa8d9 in __GI_abort () at abort.c:79
#2  0x00007f2f875054af in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f2f87614f4b "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f2f8750ca6c in malloc_printerr (str=str@entry=0x7f2f876130e0 "free(): invalid pointer") at malloc.c:5332
#4  0x00007f2f87510932 in free_check (mem=0x557344c742f0, caller=<optimized out>) at hooks.c:255
#5  0x00007f2f876d7780 in g_list_foreach (list=<optimized out>, 
    list@entry=0x557344d41740 = {...}, func=0x7f2f87511740 <__GI___libc_free>, user_data=user_data@entry=0x0)
    at ../glib/glist.c:1069
#6  0x00007f2f876d77af in g_list_free_full (list=0x557344d41740 = {...}, free_func=<optimized out>)
    at ../glib/glist.c:223
#7  0x00005573432f3b55 in select_next_page_no.isra ()
#8  0x00005573432f5bfa in on_next_btn_cb ()
#9  0x00005573432f60fe in consume_cmd_output ()
#10 0x00007f2f876db4a0 in g_main_dispatch (context=0x557344bac150) at ../glib/gmain.c:3179
#11 g_main_context_dispatch (context=context@entry=0x557344bac150) at ../glib/gmain.c:3844
#12 0x00007f2f876db830 in g_main_context_iterate
    (context=context@entry=0x557344bac150, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:3917
#13 0x00007f2f876db8d3 in g_main_context_iteration
    (context=context@entry=0x557344bac150, may_block=may_block@entry=1) at ../glib/gmain.c:3978
#14 0x00007f2f878efc75 in g_application_run
    (application=0x557344cbc0f0 [GtkApplication], argc=<optimized out>, argv=<optimized out>)
    at ../gio/gapplication.c:2559
#15 0x00005573432f00c4 in main ()
```

**Comment by ernestask** [comment]
I remember seeing this, but not anymore. I think https://github.com/abrt/libreport/commit/2b919cffbfb12f6cef55db6aa6d2a92aef454a27 fixed it. Will try to replicate, but closing in the meantime.
