### ISSUE TITLE
Traceback (most recent call last):   File "/usr/bin/reporter-bugzilla", line 709, in <module>     report = pf.generate_report()

### ISSUE THREAD

**Issue by romulasry** [abrt/libreport#780]
--- Running report_Bugzilla ---
Checking for duplicates
Traceback (most recent call last):
  File "/usr/bin/reporter-bugzilla", line 709, in <module>
    report = pf.generate_report()
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/reportclient/internal/problem_formatter.py", line 318, in generate_report
    section['items'] = self.process_section_items(section)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/reportclient/internal/problem_formatter.py", line 293, in process_section_items
    child['items'] = self.process_section_items(child)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/reportclient/internal/problem_formatter.py", line 270, in process_section_items
    short_bt = get_short_backtrace(self.problem_data, self.logger)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/reportclient/internal/problem_formatter.py", line 97, in get_short_backtrace
    truncated = backtrace.to_short_text()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
LookupError: Crash thread not found
('report_Bugzilla' exited with 1)

**Comment by romulasry** [comment]
2.17.7-1.fc39.x86_64
